In [1]:
import numpy as np

def scaled_dot_product_attention(Q, K, V):
    # Compute dot product of Q and K^T
    dot_product = np.matmul(Q, K.T)

    # Scale by square root of key dimension
    d_k = K.shape[1]
    scaled = dot_product / np.sqrt(d_k)

    # Apply softmax to get attention weights
    attention_weights = np.exp(scaled) / np.sum(np.exp(scaled), axis=-1, keepdims=True)

    # Multiply by V to get output
    output = np.matmul(attention_weights, V)

    return attention_weights, output

# Test inputs
Q = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
K = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
V = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Compute attention
weights, output = scaled_dot_product_attention(Q, K, V)

print("Attention Weights:")
print(weights)
print("\nOutput:")
print(output)

Attention Weights:
[[0.73105858 0.26894142]
 [0.26894142 0.73105858]]

Output:
[[2.07576569 3.07576569 4.07576569 5.07576569]
 [3.92423431 4.92423431 5.92423431 6.92423431]]
